"""
=======================================================
  Gesture Recognition Wearable — Phase 02
  Step 3: INT8 Quantization + TFLite Export

  Converts the trained Keras model to a TFLite flatbuffer
  with full INT8 post-training quantization. Then exports
  it as a C byte array ready to embed in the ESP8266
  Arduino firmware.

  Requirements:
    pip install tensorflow numpy

  Usage:
    python quantize_export.py

  Outputs:
    models/gesture_model_float32.tflite   (baseline)
    models/gesture_model_int8.tflite      (quantized)
    models/gesture_model.h                (C array for Arduino)
    models/quantization_report.txt        (size + accuracy comparison)
=======================================================
"""

import os
import json
import struct
import numpy as np
import tensorflow as tf

# ── Config ──────────────────────────────────────────
ROOT_DIR   = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))
DATA_DIR   = os.path.join(ROOT_DIR, "data")
MODELS_DIR = os.path.join(ROOT_DIR, "models")
WINDOW_SIZE = 50
N_FEATURES  = 6
N_REPR_SAMPLES = 200  # calibration samples for INT8 quantization

# ────────────────────────────────────────────────────
def load_model_and_data():
    model_path = os.path.join(MODELS_DIR, "gesture_model.keras")
    print(f"Loading model from {model_path} ...")
    if not os.path.exists(model_path):
        raise FileNotFoundError(
            f"Missing trained model: {model_path}. Run train_model.py first."
        )
    model = tf.keras.models.load_model(model_path)

    X_train = np.load(os.path.join(DATA_DIR, "X_train.npy"))
    X_test  = np.load(os.path.join(DATA_DIR, "X_test.npy"))
    y_test  = np.load(os.path.join(DATA_DIR, "y_test.npy"))

    with open(os.path.join(DATA_DIR, "label_map.json")) as f:
        label_map = json.load(f)

    return model, X_train, X_test, y_test, label_map

def representative_dataset(X_train: np.ndarray):
    """
    Generator that yields calibration samples for INT8 quantization.
    TFLite uses these to determine the dynamic range of each layer.
    """
    indices = np.random.choice(len(X_train), N_REPR_SAMPLES, replace=False)
    for i in indices:
        sample = X_train[i:i+1].astype(np.float32)  # shape (1, 50, 6)
        yield [sample]

def convert_float32(model) -> bytes:
    """Standard TFLite conversion, no quantization."""
    converter = tf.lite.TFLiteConverter.from_keras_model(model)
    tflite_model = converter.convert()
    return tflite_model

def convert_int8(model, X_train: np.ndarray) -> bytes:
    """
    Full integer quantization (activations + weights both INT8).
    Requires representative dataset for calibration.
    """
    converter = tf.lite.TFLiteConverter.from_keras_model(model)
    converter.optimizations = [tf.lite.Optimize.DEFAULT]
    converter.representative_dataset = lambda: representative_dataset(X_train)
    converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS_INT8]
    converter.inference_input_type  = tf.int8
    converter.inference_output_type = tf.int8
    tflite_model = converter.convert()
    return tflite_model

def evaluate_tflite(tflite_bytes: bytes, X_test: np.ndarray, y_test: np.ndarray,
                    is_int8: bool = False) -> float:
    """Run TFLite interpreter on test set and return accuracy."""
    interpreter = tf.lite.Interpreter(model_content=tflite_bytes)
    interpreter.allocate_tensors()

    input_details  = interpreter.get_input_details()
    output_details = interpreter.get_output_details()

    correct = 0
    for i in range(len(X_test)):
        sample = X_test[i:i+1].astype(np.float32)

        if is_int8:
            # Quantize input: float -> int8
            scale, zero_point = input_details[0]["quantization"]
            sample = (sample / scale + zero_point).astype(np.int8)

        interpreter.set_tensor(input_details[0]["index"], sample)
        interpreter.invoke()
        output = interpreter.get_tensor(output_details[0]["index"])

        if is_int8:
            # Dequantize output
            scale, zero_point = output_details[0]["quantization"]
            output = (output.astype(np.float32) - zero_point) * scale

        pred = np.argmax(output)
        if pred == y_test[i]:
            correct += 1

    return correct / len(X_test)

def to_c_array(tflite_bytes: bytes, var_name: str = "gesture_model") -> str:
    """
    Converts a TFLite flatbuffer to a C header file.
    This is what gets embedded in the Arduino firmware.
    """
    hex_values = [f"0x{b:02x}" for b in tflite_bytes]
    num_bytes  = len(tflite_bytes)

    # Format into rows of 12 hex values
    rows = []
    for i in range(0, num_bytes, 12):
        row = ", ".join(hex_values[i:i+12])
        rows.append(f"  {row}")

    c_array = f"""// Auto-generated by quantize_export.py
// Gesture Recognition Wearable — TFLite Model
// Model size: {num_bytes} bytes ({num_bytes/1024:.1f} KB)
// Quantization: INT8

#ifndef GESTURE_MODEL_H
#define GESTURE_MODEL_H

#include <pgmspace.h>

const unsigned int {var_name}_len = {num_bytes};

const unsigned char {var_name}[] PROGMEM = {{
{chr(10).join(rows)}
}};

#endif // GESTURE_MODEL_H
"""
    return c_array

def write_report(paths: dict, sizes: dict, accuracies: dict, label_map: dict):
    lines = [
        "=" * 54,
        "  Gesture Wearable — Quantization Report",
        "=" * 54,
        "",
        "Model files:",
    ]
    for key, path in paths.items():
        lines.append(f"  {key:20s} -> {path}")

    lines += [
        "",
        "Size comparison:",
        f"  {'float32 tflite':20s} : {sizes['float32']:>8} bytes  ({sizes['float32']/1024:.1f} KB)",
        f"  {'int8 tflite':20s} : {sizes['int8']:>8} bytes  ({sizes['int8']/1024:.1f} KB)",
        f"  {'Compression':20s} : {100*(1 - sizes['int8']/sizes['float32']):.1f}% smaller",
        "",
        "Accuracy on test set:",
        f"  {'Keras float32':20s} : {accuracies['keras']*100:.2f}%",
        f"  {'TFLite float32':20s} : {accuracies['float32']*100:.2f}%",
        f"  {'TFLite INT8':20s} : {accuracies['int8']*100:.2f}%",
        f"  {'Accuracy drop':20s} : {(accuracies['keras'] - accuracies['int8'])*100:.2f}%",
        "",
        "Label map:",
    ]
    for name, idx in sorted(label_map.items(), key=lambda x: x[1]):
        lines.append(f"  {idx}  ->  {name}")

    lines += [
        "",
        "Next step: copy gesture_model.h into your Arduino",
        "firmware folder and proceed to Phase 03.",
        "=" * 54,
    ]
    return "\n".join(lines)

# ── Main ─────────────────────────────────────────────
def main():
    os.makedirs(MODELS_DIR, exist_ok=True)
    np.random.seed(42)

    model, X_train, X_test, y_test, label_map = load_model_and_data()

    # Baseline Keras accuracy
    print("\nBaseline Keras test accuracy ...")
    keras_acc = model.evaluate(X_test, y_test, verbose=0)[1]
    print(f"  Keras float32 accuracy : {keras_acc*100:.2f}%")

    # Float32 TFLite
    print("\nConverting to float32 TFLite ...")
    f32_bytes = convert_float32(model)
    f32_path  = os.path.join(MODELS_DIR, "gesture_model_float32.tflite")
    with open(f32_path, "wb") as f:
        f.write(f32_bytes)
    print(f"  Saved -> {f32_path}  ({len(f32_bytes)} bytes)")

    print("  Evaluating float32 TFLite ...")
    f32_acc = evaluate_tflite(f32_bytes, X_test, y_test, is_int8=False)
    print(f"  TFLite float32 accuracy : {f32_acc*100:.2f}%")

    # INT8 TFLite
    print("\nConverting to INT8 TFLite (calibrating with representative dataset) ...")
    int8_bytes = convert_int8(model, X_train)
    int8_path  = os.path.join(MODELS_DIR, "gesture_model_int8.tflite")
    with open(int8_path, "wb") as f:
        f.write(int8_bytes)
    print(f"  Saved -> {int8_path}  ({len(int8_bytes)} bytes)")

    print("  Evaluating INT8 TFLite ...")
    int8_acc = evaluate_tflite(int8_bytes, X_test, y_test, is_int8=True)
    print(f"  TFLite INT8 accuracy    : {int8_acc*100:.2f}%")

    acc_drop = (keras_acc - int8_acc) * 100
    if acc_drop > 3.0:
        print(f"  ⚠  Accuracy drop of {acc_drop:.2f}% is above 3%. Consider more calibration samples.")
    else:
        print(f"  ✓  Accuracy drop of {acc_drop:.2f}% is within acceptable range.")

    # C array header
    print("\nGenerating C header for Arduino ...")
    c_header  = to_c_array(int8_bytes, var_name="gesture_model")
    h_path    = os.path.join(MODELS_DIR, "gesture_model.h")
    with open(h_path, "w") as f:
        f.write(c_header)
    print(f"  Saved -> {h_path}")

    # Report
    paths = {
        "float32 tflite": f32_path,
        "int8 tflite":    int8_path,
        "C header":       h_path,
    }
    sizes = {
        "float32": len(f32_bytes),
        "int8":    len(int8_bytes),
    }
    accuracies = {
        "keras":   keras_acc,
        "float32": f32_acc,
        "int8":    int8_acc,
    }
    report = write_report(paths, sizes, accuracies, label_map)
    report_path = os.path.join(MODELS_DIR, "quantization_report.txt")
    with open(report_path, "w") as f:
        f.write(report)

    print(f"\n{'='*54}")
    print(report)
    print(f"\n  Full report saved -> {report_path}")
    print("  Phase 02 complete. Proceed to Phase 03 (on-device inference firmware).\n")

if __name__ == "__main__":
    main()
