; =====================================================
;  Gesture Recognition Wearable — Phase 03
;  PlatformIO Project Configuration
;  Board: ESP8266 NodeMCU / Wemos D1 Mini
; =====================================================

[env:esp8266]
platform  = espressif8266
board     = nodemcuv2          ; change to d1_mini if using Wemos D1 Mini
framework = arduino
build_src_filter = +<main.cpp>
monitor_filters = esp8266_exception_decoder
; Serial monitor
monitor_speed = 115200

; Build flags
build_flags =
  -I include
  -D ARDUINO_ESP8266
  -O2
  -Wno-unused-variable

upload_speed = 921600

[env:data]
platform = espressif8266
board = nodemcuv2
framework = arduino
build_src_filter = +<data_collection.cpp> +<common/*>
monitor_speed = 115200
upload_speed = 921600